### ISSUE TITLE
DecklinkOutput uses high GPU load

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProDeckLink#17]
When using DeckLinkOutput component, vsync is disabled to get the best accuracy for rendering the output frames.  This can be very wasteful and puts a high GPU and CPU load.  

It would be nice to improve this.  Either with the new method for rendering, or by adding some delays in there so that if it's running way too fast it will not max out the system.

**Comment by HaruHappy** [comment]
how to set delay?

**Comment by AndrewRH** [comment]
You could add a System.Threading.Thread.Sleep(8) into an Update() for example.

**Comment by HaruHappy** [comment]
> You could add a System.Threading.Thread.Sleep(8) into an Update() for example.

i found a solution,set application.targetfram = 60     the cpu and gpu will going down

**Comment by v2k** [comment]
Also noticing this is more of an issue after upgrading from 1.6.6 to 1.8.6; is setting the target frame rate the only work around?

**Comment by AndrewRH** [comment]
We're looking into this now and will hopefully have more information by the end of the week

**Comment by RenderHeadsMrT** [comment]
This issue may well have been linked to 'multi-output' being selected (if if only a single output was used) which would force Unity to run as quickly as possible. We've now automated this feature to only use multi-output mode if multiple outputs are in use and also limited Unity to a factor of the output rates instead of unbounded.
