### ISSUE TITLE
Black video untill started camera in (for example) OBS

### ISSUE THREAD

**Issue by gijsbeijer** [RenderHeads/UnityPlugin-AVProDeckLink#35]
Hi,

Posting it here as I don't know if it is actually a bug, and it's definitely not a feature request. Appologies if I misunderstood.

I'm using the AVProLive camera plugin (2.9.0) with a BlackMagic decklink card, a BlackMagic pocket cinema 6K and Unity 2020.1.12f.

In my setup and also in the example scenes I always get black video (after a reboot) untill I start the camera in a third party program (e.g. OBS), after that it runs as expected every time I start my scene.

Steps to reproduce:
* reboot
* play a sample scene (e.g. MaterialMappingDemo)
* see black video
* open OBS (see the camera feed)
* play a sample scene
* it works

Expected result:
Camera feed shows up first time and without having to start the camera via a third party software first)

Regards,
Gijs

**Comment by kahnivore** [comment]
Hi Gijs

We recommend you try this setup using the AVPro DeckLink plugin instead of AVPro LiveCamera. Trial version can be found here: http://renderheads.com/downloads/ 
The DeckLink plugin will be able to auto-detect the correct mode for your hardware, whereas with LiveCamera you need to select the exact mode in order to not get blackness. 

Please let us know if this solves your problem and if there's anything more we can do to help.
