### ISSUE TITLE
Frame drop on AVProDeckLink

### ISSUE THREAD

**Issue by sidetail09** [RenderHeads/UnityPlugin-AVProDeckLink#7]
**Bug description**
Frame drop is occurred in binary package, but not in Unity Editor.
*We already tried another combination of versions with AVProDeckLink and DesktopVideo.
*We already tried to change input resolution from DeckLink 2K/4K 
(AVProDeckLink:1.7.2/1.7.4/1.6.6, DesktopVideo:11.1/11.2/11.3/10.11.4)
But the issue has not solved yet.

**Setup :**
 - Unity version: 2018.4.1
 - AVPro DeckLink version: 1.7.2 
 - Operating system version: Windows10Pro
 - Hardware model: DeckLink 4K Extreme(6G)
 - Cables used:HDMI1.4(UHD/30p)?
 - Desktop Video version: 11.2
 - Video mode: 2K/4K, 60p 

-  Device Detail
CPU Intel Core i7 8086K 10C20T
RAM DDR4 32GB
NIC 1G on Board
GPU Nvidia Geforce 1080Ti

- System Resource while playing
CPU: 30-40%
GPU: 10-20%

How can I solve problem?

**Comment by HaruHappy** [comment]
> **Bug description**
> Frame drop is occurred in binary package, but not in Unity Editor.
> *We already tried another combination of versions with AVProDeckLink and DesktopVideo.
> *We already tried to change input resolution from DeckLink 2K/4K
> (AVProDeckLink:1.7.2/1.7.4/1.6.6, DesktopVideo:11.1/11.2/11.3/10.11.4)
> But the issue has not solved yet.
> 
> **Setup :**
> 
> * Unity version: 2018.4.1
> * AVPro DeckLink version: 1.7.2
> * Operating system version: Windows10Pro
> * Hardware model: DeckLink 4K Extreme(6G)
> * Cables used:HDMI1.4(UHD/30p)?
> * Desktop Video version: 11.2
> * Video mode: 2K/4K, 60p
> * Device Detail
>   CPU Intel Core i7 8086K 10C20T
>   RAM DDR4 32GB
>   NIC 1G on Board
>   GPU Nvidia Geforce 1080Ti
> * System Resource while playing
>   CPU: 30-40%
>   GPU: 10-20%
> 
> How can I solve problem?

hello,are u solved this bug?

**Comment by AndrewRH** [comment]
Is it possible that your application is doing a GC (garbage collection) during output?

**Comment by kahnivore** [comment]
From keeping:

We are using AVPro DeckLink 1.8.6 with a Blackmagic 8k Pro.  We generally have two issues.

We have a render pipeline as follows:
SDI => DeckLinkInput
Read input texture, composite onto texture via command buffers
Blit resulting texture to DeckLinkOutput.InputTexture => SDI
We have had consistent results with 720p signals.  It seems solid without dropping frames.

When we have 1080p input signals, we start to notice some frame drops - occasional.

The other issue is that we sometimes end up in a poor state.  In this state, there's a steady and large amount of frame drops.  Re-initializing the input device can get this to normalize back to working, but the cause is unknown.  Changing inputs can sometimes trigger this bad state as well.

We were able to get around the issue by hacking your code.  In DeckLinkOutput::Process() - we had to make it always output the frame; i.e. forcing _canOutputFrame to true as we're always synced to input.

We've always had to do this with your plug-in to get around the issue.  Is this something you plan on addressing in future releases?

We are sync'd to input and have disabled multi output generally.
